---
title: "SHAP R Example"
author: "NStatum"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(xgboost)
library(shapviz)
library(fastshap)
library(patchwork)
```

## Simulating Data Set

A data set will be constructed with built-in relationship between the target and features.

```{r}
set.seed(123)

n <- 10000

square_feet <- rnorm(n, mean = 2000, sd = 500)
num_bedrooms <- pmin(rpois(n, lambda = 3) + 1, 6)
age_of_home <- rpois(n, lambda = 30)
distance_to_city_center <- runif(n, 0, 30)  # miles
neighborhood_quality <- rnorm(n, mean = 0, sd = 1)

sale_price <- 
  50 * square_feet + 
  8000 * num_bedrooms - 
  1000 * age_of_home + 
  20000 * sin(distance_to_city_center) +
  100000 +
  rnorm(n, sd = 10000)

df <- tibble(
  square_feet,
  num_bedrooms,
  age_of_home,
  distance_to_city_center,
  neighborhood_quality,
  sale_price
)

# Remove unneeded temporary variables
rm(n, square_feet, num_bedrooms, age_of_home, distance_to_city_center, neighborhood_quality, sale_price)
```

```{r}
ggplot(data = df, mapping = aes(x = square_feet, y = sale_price)) +
  geom_point(alpha = 0.1) +

ggplot(data = df, mapping = aes(x = num_bedrooms, y = sale_price)) +
  geom_point(alpha = 0.1) +

ggplot(data = df, mapping = aes(x = age_of_home, y = sale_price)) +
  geom_point(alpha = 0.1) +

ggplot(data = df, mapping = aes(x = distance_to_city_center, y = sale_price)) +
  geom_point(alpha = 0.1) +

ggplot(data = df, mapping = aes(x = neighborhood_quality, y = sale_price)) +
  geom_point(alpha = 0.1)
```

# Linear Regression

```{r}
lm_model <- lm(data = df, formula = sale_price ~ square_feet + num_bedrooms + age_of_home + distance_to_city_center + neighborhood_quality)
summary(lm_model)
```

```{r}
lm_shp <- fastshap::explain(lm_model, X = df %>% select(-sale_price), pred_wrapper = predict, adjust = TRUE, nsim = 100)
lm_shp_viz <- shapviz::shapviz(lm_shp, X = df %>% select(-sale_price))
```

```{r}
sv_importance(lm_shp_viz, kind = "beeswarm")
```

```{r}
sv_dependence(lm_shp_viz, v = colnames(df)[1:5], color_var = NULL, color = "royalblue4")
```

```{r}
sv_force(lm_shp_viz, row_id = 1)
sv_waterfall(lm_shp_viz, row_id = 1)
```

# XGBoost

```{r}
X <- df %>% select(-sale_price)
y_vec <- df$sale_price

dmat <- xgb.DMatrix(data = as.matrix(X), label = y_vec)

params <- list(
  objective = "reg:squarederror",
  max_depth = 6,
  eta = 0.05,
  subsample = 0.8,
  colsample_bytree = 0.8
)

xgb_model <- xgb.train(
  params = params,
  data = dmat,
  nrounds = 300,
  verbose = 0
)
```

```{r}
pred_fun <- function(object, newdata) {
  predict(object, as.matrix(newdata))
}

xg_shp <- fastshap::explain(
  object = xgb_model,
  X = X,
  pred_wrapper = pred_fun,
  nsim = 100,
  adjust = TRUE
)

xg_shp_viz <- shapviz::shapviz(xg_shp, X = X)
```

```{r}
sv_importance(xg_shp_viz, kind = "beeswarm")
```

```{r}
sv_dependence(xg_shp_viz, v = colnames(df)[1:5], color_var = NULL, color = "royalblue4")
```

```{r}
sv_force(xg_shp_viz, row_id = 1)
sv_waterfall(xg_shp_viz, row_id = 1)
```
